export interface ColorVariant {
  name: string
  swatch: string // tailwind bg color class or hex
  thumbnail: string
}

export interface FeaturedProduct {
  id: string
  handle: string
  name: string
  price: number
  originalPrice: number
  discountPercent: number
  image: string
  secondaryImage: string
  rating: number
  reviewCount: number
  hasFlash: boolean
  colors: ColorVariant[]
  collection: 'bags' | 'shoes'
  priceFrom?: boolean
}

export const featuredProducts: FeaturedProduct[] = [
  // ============ PRIME BAGS ============
  {
    id: 'bag-1',
    handle: 'croissant-chic-crossbody-bag',
    name: 'Croissant Chic Crossbody Bag',
    price: 765,
    originalPrice: 2185,
    discountPercent: 65,
    image: '/products/featured/crossbody-bag.png',
    secondaryImage: '/products/featured/crossbody-bag.png',
    rating: 4.5,
    reviewCount: 44,
    hasFlash: false,
    collection: 'bags',
    colors: [
      { name: 'Black', swatch: '#1a1a1a', thumbnail: '/products/featured/crossbody-bag.png' },
      { name: 'Brown', swatch: '#8B5E3C', thumbnail: '/products/featured/shoulder-bag.png' },
      { name: 'Dark Brown', swatch: '#5C3D2E', thumbnail: '/products/featured/butterfly-bag.png' },
      { name: 'Light Coffee', swatch: '#C4A882', thumbnail: '/products/featured/twill-bag.png' },
      { name: 'Red', swatch: '#B22222', thumbnail: '/products/featured/dumpling-bag.png' },
    ],
  },
  {
    id: 'bag-2',
    handle: 'mens-rfid-smart-pop-up-wallet',
    name: "Men's RFID Smart Pop Up Wallet",
    price: 505,
    originalPrice: 952,
    discountPercent: 47,
    image: '/products/featured/smart-wallet.png',
    secondaryImage: '/products/featured/smart-wallet.png',
    rating: 4.3,
    reviewCount: 49,
    hasFlash: false,
    collection: 'bags',
    colors: [
      { name: 'Black', swatch: '#1a1a1a', thumbnail: '/products/featured/cosmetic-bag.png' },
      { name: 'Blue', swatch: '#2E5090', thumbnail: '/products/featured/duffle-bag.png' },
      { name: 'Brown', swatch: '#8B5E3C', thumbnail: '/products/featured/smart-wallet.png' },
      { name: 'Carbon Fiber', swatch: '#3a3a3a', thumbnail: '/products/featured/crossbody-bag.png' },
      { name: 'Coffee', swatch: '#6F4E37', thumbnail: '/products/featured/shoulder-bag.png' },
    ],
  },
  {
    id: 'bag-3',
    handle: 'new-style-large-capacity-shoulder-bag',
    name: 'New Style Large-Capacity Shoulder Bag',
    price: 1645,
    originalPrice: 2350,
    discountPercent: 30,
    image: '/products/featured/shoulder-bag.png',
    secondaryImage: '/products/featured/shoulder-bag.png',
    rating: 4.5,
    reviewCount: 50,
    hasFlash: true,
    collection: 'bags',
    colors: [
      { name: 'Black Elephant', swatch: '#1a1a1a', thumbnail: '/products/featured/butterfly-bag.png' },
      { name: 'Brown Elephant', swatch: '#8B5E3C', thumbnail: '/products/featured/twill-bag.png' },
      { name: 'Off White', swatch: '#F5F0EB', thumbnail: '/products/featured/dumpling-bag.png' },
    ],
  },
  {
    id: 'bag-4',
    handle: 'butterfly-design-shoulder-bag',
    name: 'Butterfly Design Shoulder Bag',
    price: 1025,
    originalPrice: 2562,
    discountPercent: 60,
    image: '/products/featured/butterfly-bag.png',
    secondaryImage: '/products/featured/butterfly-bag.png',
    rating: 4.3,
    reviewCount: 41,
    hasFlash: true,
    collection: 'bags',
    colors: [
      { name: 'Black', swatch: '#1a1a1a', thumbnail: '/products/featured/cosmetic-bag.png' },
      { name: 'Pink', swatch: '#E8A0BF', thumbnail: '/products/featured/duffle-bag.png' },
      { name: 'Silver', swatch: '#C0C0C0', thumbnail: '/products/featured/smart-wallet.png' },
      { name: 'White', swatch: '#F5F5F5', thumbnail: '/products/featured/crossbody-bag.png' },
    ],
  },
  {
    id: 'bag-5',
    handle: 'light-weight-fitness-training-gym-duffle-bag',
    name: 'Light Weight Fitness Training Gym Duffle Bag',
    price: 1742,
    originalPrice: 2764,
    discountPercent: 37,
    image: '/products/featured/duffle-bag.png',
    secondaryImage: '/products/featured/duffle-bag.png',
    rating: 4.4,
    reviewCount: 44,
    hasFlash: true,
    collection: 'bags',
    colors: [
      { name: 'Black', swatch: '#1a1a1a', thumbnail: '/products/featured/shoulder-bag.png' },
      { name: 'Blue', swatch: '#2E5090', thumbnail: '/products/featured/butterfly-bag.png' },
      { name: 'Green', swatch: '#4A7C59', thumbnail: '/products/featured/twill-bag.png' },
      { name: 'Pink', swatch: '#E8A0BF', thumbnail: '/products/featured/dumpling-bag.png' },
      { name: 'White', swatch: '#F5F5F5', thumbnail: '/products/featured/cosmetic-bag.png' },
    ],
  },
  {
    id: 'bag-6',
    handle: 'the-luxe-large-capacity-cosmetic-bag',
    name: 'The Luxe Large-Capacity Cosmetic Bag',
    price: 1298,
    originalPrice: 2093,
    discountPercent: 38,
    image: '/products/featured/cosmetic-bag.png',
    secondaryImage: '/products/featured/cosmetic-bag.png',
    rating: 4.5,
    reviewCount: 41,
    hasFlash: false,
    collection: 'bags',
    colors: [
      { name: 'Classic Black', swatch: '#1a1a1a', thumbnail: '/products/featured/duffle-bag.png' },
      { name: 'Milky White', swatch: '#F5F0EB', thumbnail: '/products/featured/smart-wallet.png' },
      { name: 'Mocha Brown', swatch: '#6F4E37', thumbnail: '/products/featured/crossbody-bag.png' },
    ],
  },
  {
    id: 'bag-7',
    handle: 'elevated-twill-crossbody-bag',
    name: 'Elevated Twill Crossbody Bag',
    price: 1123,
    originalPrice: 1781,
    discountPercent: 37,
    image: '/products/featured/twill-bag.png',
    secondaryImage: '/products/featured/twill-bag.png',
    rating: 4.5,
    reviewCount: 42,
    hasFlash: true,
    collection: 'bags',
    colors: [
      { name: 'Black', swatch: '#1a1a1a', thumbnail: '/products/featured/shoulder-bag.png' },
      { name: 'Grey', swatch: '#9CA3AF', thumbnail: '/products/featured/butterfly-bag.png' },
      { name: 'Pink', swatch: '#E8A0BF', thumbnail: '/products/featured/twill-bag.png' },
      { name: 'White', swatch: '#F5F5F5', thumbnail: '/products/featured/dumpling-bag.png' },
    ],
  },
  {
    id: 'bag-8',
    handle: 'versatile-dumpling-shoulder-bag',
    name: 'Versatile Dumpling Shoulder Bag',
    price: 2199,
    originalPrice: 2498,
    discountPercent: 12,
    image: '/products/featured/dumpling-bag.png',
    secondaryImage: '/products/featured/dumpling-bag.png',
    rating: 4.3,
    reviewCount: 42,
    hasFlash: true,
    collection: 'bags',
    colors: [
      { name: 'Khaki', swatch: '#C3B091', thumbnail: '/products/featured/cosmetic-bag.png' },
      { name: 'White', swatch: '#F5F5F5', thumbnail: '/products/featured/duffle-bag.png' },
    ],
  },

  // ============ PRIME SHOES ============
  {
    id: 'shoe-1',
    handle: 'breathable-soft-sole-fashion-loafers',
    name: 'Breathable Soft-Sole Fashion Loafers',
    price: 2318,
    originalPrice: 2898,
    discountPercent: 20,
    image: '/products/featured/fashion-loafers.png',
    secondaryImage: '/products/featured/fashion-loafers.png',
    rating: 4.4,
    reviewCount: 41,
    hasFlash: true,
    collection: 'shoes',
    priceFrom: true,
    colors: [
      { name: 'Beige', swatch: '#D4B896', thumbnail: '/products/featured/british-loafers.png' },
      { name: 'Black', swatch: '#1a1a1a', thumbnail: '/products/featured/fashion-loafers.png' },
      { name: 'Deep Blue', swatch: '#1E3A5F', thumbnail: '/products/featured/casual-sneakers.png' },
    ],
  },
  {
    id: 'shoe-2',
    handle: 'urban-lite-low-top-casual-sneakers',
    name: 'Urban Lite Low-Top Casual Sneakers',
    price: 2920,
    originalPrice: 3650,
    discountPercent: 20,
    image: '/products/featured/casual-sneakers.png',
    secondaryImage: '/products/featured/casual-sneakers.png',
    rating: 4.3,
    reviewCount: 70,
    hasFlash: true,
    collection: 'shoes',
    colors: [
      { name: 'Beige', swatch: '#D4B896', thumbnail: '/products/featured/suede-loafers.png' },
      { name: 'Black', swatch: '#1a1a1a', thumbnail: '/products/featured/moccasin-loafers.png' },
      { name: 'Green', swatch: '#4A7C59', thumbnail: '/products/featured/runner-shoes.png' },
    ],
  },
  {
    id: 'shoe-3',
    handle: 'mens-suede-finish-slip-on-open-back-loafers',
    name: "Men's Suede Finish Slip On Open Back Loafers",
    price: 2950,
    originalPrice: 3687,
    discountPercent: 20,
    image: '/products/featured/suede-loafers.png',
    secondaryImage: '/products/featured/suede-loafers.png',
    rating: 4.5,
    reviewCount: 21,
    hasFlash: true,
    collection: 'shoes',
    colors: [
      { name: 'Black', swatch: '#1a1a1a', thumbnail: '/products/featured/fisherman-loafers.png' },
      { name: 'Blue', swatch: '#2E5090', thumbnail: '/products/featured/urban-sneakers.png' },
      { name: 'Khaki', swatch: '#C3B091', thumbnail: '/products/featured/british-loafers.png' },
    ],
  },
  {
    id: 'shoe-4',
    handle: 'men-s-slip-on-moccasin-loafers',
    name: "Men's Slip-On Moccasin Loafers",
    price: 2614,
    originalPrice: 3268,
    discountPercent: 20,
    image: '/products/featured/moccasin-loafers.png',
    secondaryImage: '/products/featured/moccasin-loafers.png',
    rating: 4.4,
    reviewCount: 20,
    hasFlash: true,
    collection: 'shoes',
    colors: [
      { name: 'Brown', swatch: '#8B5E3C', thumbnail: '/products/featured/fashion-loafers.png' },
      { name: 'Coffee Brown', swatch: '#6F4E37', thumbnail: '/products/featured/casual-sneakers.png' },
      { name: 'Light Gray', swatch: '#9CA3AF', thumbnail: '/products/featured/suede-loafers.png' },
      { name: 'Sand', swatch: '#D4B896', thumbnail: '/products/featured/moccasin-loafers.png' },
    ],
  },
  {
    id: 'shoe-5',
    handle: 'men-s-velocity-sport-high-runner-shoes',
    name: "Men's Velocity Sport High Runner Shoes",
    price: 3797,
    originalPrice: 4746,
    discountPercent: 20,
    image: '/products/featured/runner-shoes.png',
    secondaryImage: '/products/featured/runner-shoes.png',
    rating: 4.5,
    reviewCount: 15,
    hasFlash: true,
    collection: 'shoes',
    colors: [
      { name: 'White/Black', swatch: '#E8E8E8', thumbnail: '/products/featured/runner-shoes.png' },
      { name: 'White/Black Strips', swatch: '#D0D0D0', thumbnail: '/products/featured/fisherman-loafers.png' },
      { name: 'White/Grey', swatch: '#C8C8C8', thumbnail: '/products/featured/urban-sneakers.png' },
      { name: 'White/Grey Strips', swatch: '#B8B8B8', thumbnail: '/products/featured/british-loafers.png' },
    ],
  },
  {
    id: 'shoe-6',
    handle: 'men-s-linen-breathable-fisherman-loafers',
    name: "Men's Linen Breathable Fisherman Loafers",
    price: 2658,
    originalPrice: 3322,
    discountPercent: 20,
    image: '/products/featured/fisherman-loafers.png',
    secondaryImage: '/products/featured/fisherman-loafers.png',
    rating: 4.5,
    reviewCount: 21,
    hasFlash: true,
    collection: 'shoes',
    priceFrom: true,
    colors: [
      { name: 'Beige', swatch: '#D4B896', thumbnail: '/products/featured/fashion-loafers.png' },
      { name: 'Black', swatch: '#1a1a1a', thumbnail: '/products/featured/casual-sneakers.png' },
    ],
  },
  {
    id: 'shoe-7',
    handle: 'trend-core-urban-style-sneakers',
    name: 'Trend Core Urban Style Sneakers',
    price: 2698,
    originalPrice: 3372,
    discountPercent: 20,
    image: '/products/featured/urban-sneakers.png',
    secondaryImage: '/products/featured/urban-sneakers.png',
    rating: 4.2,
    reviewCount: 38,
    hasFlash: true,
    collection: 'shoes',
    colors: [
      { name: 'Blue', swatch: '#2E5090', thumbnail: '/products/featured/suede-loafers.png' },
      { name: 'Green', swatch: '#4A7C59', thumbnail: '/products/featured/moccasin-loafers.png' },
    ],
  },
  {
    id: 'shoe-8',
    handle: 'fashionable-british-style-loafers',
    name: 'Fashionable British Style Loafers',
    price: 3487,
    originalPrice: 4359,
    discountPercent: 20,
    image: '/products/featured/british-loafers.png',
    secondaryImage: '/products/featured/british-loafers.png',
    rating: 4.7,
    reviewCount: 20,
    hasFlash: true,
    collection: 'shoes',
    colors: [
      { name: 'Black', swatch: '#1a1a1a', thumbnail: '/products/featured/runner-shoes.png' },
      { name: 'Brown', swatch: '#8B5E3C', thumbnail: '/products/featured/fisherman-loafers.png' },
      { name: 'Gray', swatch: '#9CA3AF', thumbnail: '/products/featured/urban-sneakers.png' },
    ],
  },
]
