import { db } from '@/lib/db'
import { NextResponse } from 'next/server'

const products = [
  // Women's Bags - Crossbody, Shoulder, Tote, Mini
  {
    name: 'Croissant Chic Crossbody Bag',
    description: 'Elegant crescent-shaped crossbody bag crafted from premium leather with adjustable strap. Available in Black, Brown, Dark Brown, Light Coffee, and Red. Perfect for everyday elegance.',
    price: 32.99,
    category: 'women',
    image: '/products/women-crossbody-bag.png',
    features: 'Premium leather|Adjustable crossbody strap|Zip-top closure|Interior slip pocket|Gold-tone hardware',
    rating: 4.5,
    inStock: true,
    badge: 'Best Seller',
  },
  {
    name: 'Butterfly Design Shoulder Bag',
    description: 'Stunning butterfly-motif shoulder bag with intricate detailing. Available in Black, Pink, Silver, and White. A statement piece that elevates any outfit.',
    price: 42.99,
    category: 'women',
    image: '/products/women-shoulder-bag.png',
    features: 'Premium vegan leather|Butterfly motif design|Magnetic flap closure|Interior zip pocket|Detachable chain strap',
    rating: 4.3,
    inStock: true,
    badge: 'New',
  },
  {
    name: 'New Style Large-Capacity Shoulder Bag',
    description: 'Spacious shoulder bag with elephant texture pattern. Available in Black, Brown, and Off White. Combines functionality with sophisticated style for the modern woman.',
    price: 68.99,
    category: 'women',
    image: '/products/women-tote-bag.png',
    features: 'Premium leather|Elephant texture pattern|Large capacity|Interior zip divider|Top handle + shoulder strap',
    rating: 4.5,
    inStock: true,
    badge: 'Premium',
  },
  {
    name: 'Elevated Twill Crossbody Bag',
    description: 'Sleek twill crossbody bag with minimalist design. Available in Black, Grey, Pink, and White. Lightweight and perfect for on-the-go lifestyles.',
    price: 46.99,
    category: 'women',
    image: '/products/women-mini-bag.png',
    features: 'Twill fabric|Adjustable strap|Zip closure|Interior card slots|Lightweight design',
    rating: 4.5,
    inStock: true,
    badge: 'Popular',
  },
  {
    name: 'Versatile Dumpling Shoulder Bag',
    description: 'Trendy dumpling-shaped shoulder bag with curved silhouette. Available in Khaki and White. The perfect blend of style and practicality for daily use.',
    price: 91.99,
    category: 'women',
    image: '/products/women-hand-bag.png',
    features: 'Premium leather|Curved dumpling shape|Magnetic closure|Interior compartments|Adjustable strap',
    rating: 4.3,
    inStock: true,
    badge: 'New',
  },
  {
    name: 'GBB Exclusive Cow Leather Tote Handbag',
    description: 'Premium cow leather tote handbag with spacious interior and elegant gold-tone hardware. Perfect for everyday luxury with multiple compartments for organized storage.',
    price: 149.99,
    category: 'women',
    image: '/products/women-hand-bag-2.png',
    features: 'Genuine cow leather|Spacious interior|Gold-tone hardware|Interior zip pocket|Adjustable strap',
    rating: 4.8,
    inStock: true,
    badge: 'Best Seller',
  },
  // Men's Bags & Wallets
  {
    name: "Men's RFID Smart Pop Up Wallet",
    description: 'Innovative pop-up card holder with RFID blocking technology. Available in Black, Blue, Brown, Carbon Fiber, and Coffee. Quick-access mechanism for your most-used cards.',
    price: 21.99,
    category: 'men',
    image: '/products/men-long-wallet.png',
    features: 'RFID blocking|Pop-up card mechanism|Aluminum frame|6 card slots|Cash pocket',
    rating: 4.3,
    inStock: true,
    badge: 'Popular',
  },
  {
    name: 'Light Weight Fitness Training Gym Duffle Bag',
    description: 'Durable lightweight duffle bag perfect for gym and travel. Available in Black, Blue, Green, Pink, and White. Features separate shoe compartment and wet pocket.',
    price: 72.99,
    category: 'men',
    image: '/products/men-backpack.png',
    features: 'Lightweight nylon|Shoe compartment|Wet/dry pocket|Adjustable shoulder strap|Water-resistant',
    rating: 4.4,
    inStock: true,
    badge: 'New',
  },
  {
    name: 'The Luxe Large-Capacity Cosmetic Bag',
    description: 'Elegant cosmetic bag with spacious interior. Available in Classic Black, Milky White, and Mocha Brown. Keeps your beauty essentials organized in style.',
    price: 54.99,
    category: 'men',
    image: '/products/men-messenger-bag.png',
    features: 'Premium PU leather|Large capacity|Multiple compartments|Waterproof lining|Portable handle',
    rating: 4.5,
    inStock: true,
    badge: 'Premium',
  },
  {
    name: 'Premium Leather Backpack - Dark Brown',
    description: 'Sophisticated dark brown leather backpack with brass buckles and padded laptop compartment. Combines style with functionality for the modern professional.',
    price: 199.99,
    category: 'men',
    image: '/products/men-backpack.png',
    features: 'Full-grain leather|Brass buckles|Padded laptop compartment|Water-resistant|Ergonomic straps',
    rating: 4.9,
    inStock: true,
    badge: 'Premium',
  },
  // Shoes
  {
    name: 'Breathable Soft-Sole Fashion Loafers',
    description: 'Comfortable breathable loafers with soft sole design. Available in Beige, Black, and Deep Blue. Perfect for all-day wear with cushioned insole.',
    price: 96.99,
    category: 'shoes',
    image: '/products/men-shoes.png',
    features: 'Breathable mesh|Soft cushioned sole|Slip-on design|Lightweight|Non-slip outsole',
    rating: 4.4,
    inStock: true,
    badge: 'Best Seller',
  },
  {
    name: 'Urban Lite Low-Top Casual Sneakers',
    description: 'Stylish low-top casual sneakers for everyday wear. Available in Beige, Black, and Green. Combines street style with premium comfort technology.',
    price: 121.99,
    category: 'shoes',
    image: '/products/women-shoes.png',
    features: 'Premium canvas|Cushioned midsole|Rubber outsole|Padded collar|Lace-up closure',
    rating: 4.3,
    inStock: true,
    badge: 'New',
  },
  {
    name: "Men's Suede Finish Slip On Open Back Loafers",
    description: 'Elegant slip-on loafers with suede finish and open back design. Available in Black, Blue, and Khaki. Premium comfort meets sophisticated style.',
    price: 123.99,
    category: 'shoes',
    image: '/products/men-shoes.png',
    features: 'Suede finish|Open back design|Cushioned footbed|Flexible sole|Slip-on convenience',
    rating: 4.5,
    inStock: true,
    badge: 'Popular',
  },
  {
    name: "Men's Slip-On Moccasin Loafers",
    description: 'Classic moccasin loafers with hand-stitched detailing. Available in Brown, Coffee Brown, Light Gray, and Sand Color. Timeless elegance for the modern gentleman.',
    price: 109.99,
    category: 'shoes',
    image: '/products/women-shoes.png',
    features: 'Genuine leather|Hand-stitched moccasin|Cushioned insole|Rubber sole|Classic design',
    rating: 4.4,
    inStock: true,
    badge: 'Premium',
  },
  {
    name: "Men's Velocity Sport High Runner Shoes",
    description: 'High-performance sport runner shoes with advanced cushioning. Available in White/Black, White/Black Strips, White/Grey, and White/Grey Strips. Built for speed and comfort.',
    price: 158.99,
    category: 'shoes',
    image: '/products/men-shoes.png',
    features: 'Mesh upper|Air cushion sole|Breathable lining|Shock absorption|Reflective details',
    rating: 4.5,
    inStock: true,
    badge: 'Best Seller',
  },
  {
    name: "Men's Linen Breathable Fisherman Loafers",
    description: 'Breathable linen fisherman loafers with woven upper. Available in Beige and Black. Perfect for warm-weather style with all-day comfort.',
    price: 110.99,
    category: 'shoes',
    image: '/products/women-shoes.png',
    features: 'Linen woven upper|Breathable design|Cushioned sole|Slip-resistant|Lightweight',
    rating: 4.5,
    inStock: true,
    badge: 'New',
  },
  {
    name: 'Trend Core Urban Style Sneakers',
    description: 'Fashion-forward urban sneakers with bold color blocking. Available in Blue and Green. Street-ready style with premium comfort features.',
    price: 112.99,
    category: 'shoes',
    image: '/products/men-shoes.png',
    features: 'Color-block design|Padded ankle|Cushioned midsole|Durable outsole|Lace-up front',
    rating: 4.2,
    inStock: true,
    badge: 'Popular',
  },
  {
    name: 'Fashionable British Style Loafers',
    description: 'Refined British-style loafers with premium leather construction. Available in Black, Brown, and Gray. Classic sophistication for formal and business occasions.',
    price: 145.99,
    category: 'shoes',
    image: '/products/women-shoes.png',
    features: 'Premium leather|British style|Leather sole|Goodyear welt|Handcrafted',
    rating: 4.7,
    inStock: true,
    badge: 'Premium',
  },
  // Belt
  {
    name: 'Classic Leather Belt - Black',
    description: 'Premium black leather belt with silver buckle, crafted from full-grain leather. A wardrobe essential that pairs perfectly with both formal and casual attire.',
    price: 39.99,
    category: 'belt',
    image: '/products/men-belt.png',
    features: 'Full-grain leather|Silver buckle|1.25 inch width|5 hole adjustment|Gift box included',
    rating: 4.5,
    inStock: true,
    badge: null,
  },
  {
    name: "Elegant Women's Belt - Tan",
    description: 'Refined tan leather belt with gold buckle detail. This versatile accessory adds a touch of elegance to dresses, skirts, and high-waisted pants.',
    price: 34.99,
    category: 'belt',
    image: '/products/women-belt.png',
    features: 'Genuine leather|Gold buckle|Slim profile|1 inch width|Adjustable fit',
    rating: 4.4,
    inStock: true,
    badge: 'New',
  },
  // Kids
  {
    name: "Kids' Mini Backpack - Pastel",
    description: 'Adorable pastel mini backpack designed for kids with fun colors and durable construction. Lightweight and spacious enough for school or play dates.',
    price: 29.99,
    category: 'kids',
    image: '/products/kids-backpack.png',
    features: 'Durable nylon|Fun pastel colors|Padded straps|Multiple pockets|Easy-clean material',
    rating: 4.6,
    inStock: true,
    badge: 'New',
  },
  // Accessories
  {
    name: 'Leather Key Holder - Brown',
    description: 'Premium brown leather key holder with brass ring and compact design. A small luxury that keeps your keys organized while adding a touch of elegance to your daily carry.',
    price: 19.99,
    category: 'accessories',
    image: '/products/leather-key-holder.png',
    features: 'Genuine leather|Brass key ring|Holds 4-6 keys|Compact design|Gift box included',
    rating: 4.3,
    inStock: true,
    badge: 'Popular',
  },
]

export async function POST() {
  try {
    // Always re-seed: delete existing products first
    const existing = await db.product.count()
    if (existing > 0) {
      // Delete all order items first (they reference products), then orders, then products
      await db.orderItem.deleteMany()
      await db.order.deleteMany()
      await db.product.deleteMany()
    }

    const created = await db.product.createMany({ data: products })
    return NextResponse.json({ message: 'Database seeded successfully', count: created.count })
  } catch (error) {
    console.error('Seed error:', error)
    return NextResponse.json({ error: 'Failed to seed database' }, { status: 500 })
  }
}
